# Generated by Django 3.2.5 on 2021-09-01 16:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bussiness_Partner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bp_full_name', models.CharField(max_length=100)),
                ('bp_designation', models.CharField(max_length=100)),
                ('bp_email', models.EmailField(max_length=254)),
                ('bp_number', models.IntegerField()),
                ('company_name', models.CharField(max_length=100)),
                ('company_address', models.TextField()),
                ('communication_address', models.TextField()),
                ('incorporation_year', models.IntegerField()),
                ('founder_full_name', models.CharField(max_length=100)),
                ('founder_email', models.EmailField(max_length=254)),
                ('founder_number', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Entrepreneurs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ent_full_name', models.CharField(max_length=100)),
                ('ent_email', models.EmailField(max_length=254)),
                ('ent_number', models.IntegerField()),
                ('ent_area', models.CharField(max_length=200)),
                ('ent_pincode', models.IntegerField()),
                ('ent_address', models.TextField()),
                ('ent_aadhar', models.IntegerField()),
                ('ent_photo', models.ImageField(upload_to='entrepreneurs')),
                ('ent_address_proof', models.FileField(upload_to='entrepreneurs')),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=100)),
                ('product_description', models.TextField()),
                ('product_price', models.IntegerField(default=0)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='website.bussiness_partner')),
            ],
        ),
        migrations.CreateModel(
            name='Product_Video',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_video', models.FileField(upload_to='product_video')),
            ],
        ),
        migrations.CreateModel(
            name='Product_Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_image', models.ImageField(upload_to='product_images')),
                ('product_img_description', models.TextField()),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='website.product')),
            ],
        ),
        migrations.CreateModel(
            name='FAQ',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.TextField()),
                ('answer', models.TextField()),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='website.product')),
            ],
        ),
    ]
