# Generated by Django 3.2.5 on 2021-09-04 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0002_auto_20210904_2023'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product_image',
            name='product_video',
        ),
        migrations.AddField(
            model_name='product',
            name='product_video',
            field=models.FileField(null=True, upload_to='product_video'),
        ),
    ]
