# Generated by Django 3.2.5 on 2021-09-04 22:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0005_alter_entrepreneurs_ent_pincode'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bussiness_partner',
            name='bp_number',
            field=models.DecimalField(decimal_places=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='bussiness_partner',
            name='founder_number',
            field=models.DecimalField(decimal_places=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='bussiness_partner',
            name='incorporation_year',
            field=models.DecimalField(decimal_places=0, max_digits=4),
        ),
    ]
