# Generated by Django 3.2.5 on 2021-09-05 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0006_auto_20210905_0354'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='faq',
            name='product',
        ),
        migrations.RemoveField(
            model_name='product_image',
            name='product',
        ),
        migrations.AddField(
            model_name='product',
            name='faq',
            field=models.ManyToManyField(to='website.FAQ'),
        ),
        migrations.AddField(
            model_name='product',
            name='product_image',
            field=models.ManyToManyField(to='website.Product_Image'),
        ),
    ]
