# Generated by Django 3.2.5 on 2021-09-11 15:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('website', '0009_auto_20210910_2100'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bussiness_partner',
            name='user',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bp', to=settings.AUTH_USER_MODEL),
        ),
    ]
