# Generated by Django 3.2.5 on 2021-09-12 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0010_alter_bussiness_partner_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='bussiness_partner',
            name='status',
            field=models.IntegerField(choices=[(0, 'pending'), (1, 'active')], default=0),
        ),
        migrations.AddField(
            model_name='entrepreneurs',
            name='status',
            field=models.IntegerField(choices=[(0, 'pending'), (1, 'active')], default=0),
        ),
    ]
