# Generated by Django 3.2.5 on 2021-09-12 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0011_auto_20210912_1602'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bussiness_partner',
            name='status',
            field=models.IntegerField(choices=[(0, 'pending'), (1, 'active'), (-1, 'rejected')], default=0),
        ),
        migrations.AlterField(
            model_name='entrepreneurs',
            name='status',
            field=models.IntegerField(choices=[(0, 'pending'), (1, 'active'), (-1, 'rejected')], default=0),
        ),
    ]
