# Generated by Django 3.2.5 on 2021-09-24 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0015_auto_20210925_0019'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.ManyToManyField(null=True, related_name='products', to='website.Categories'),
        ),
    ]
