# Generated by Django 3.2.5 on 2021-09-25 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0016_alter_product_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entrepreneurs',
            name='ent_pincode',
            field=models.DecimalField(decimal_places=0, max_digits=6),
        ),
    ]
