# Generated by Django 3.2.5 on 2021-09-29 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0019_product_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='product_id',
            field=models.IntegerField(default=1, unique=True),
        ),
    ]
